
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 19 2024 15:29:23 IST (Jun 19 2024 09:59:23 UTC)

// Verification Directory fv/mac16arr 

module fag_56(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  AOI2BB1XL g24__2398(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  AND2X2 g2__5107(.A (a), .B (b), .Y (c));
endmodule

module fag_86(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_2;
  OAI2BB1X2 g95__6260(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  XOR2X1 g96__4319(.A (n_1), .B (cin), .Y (s));
  OAI21X1 g97__8428(.A0 (a), .A1 (b), .B0 (cin), .Y (n_2));
  XOR2X1 g98__5526(.A (a), .B (b), .Y (n_1));
endmodule

module fag_85(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g92__6783(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g93__3680(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g94__1617(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g95__2802(.A (a), .B (b), .Y (n_0));
endmodule

module fag_84(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g65__1705(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g66__5122(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g67__8246(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g68__7098(.A (a), .B (b), .Y (n_0));
endmodule

module fag_83(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g65__6131(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g66__1881(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g67__5115(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g68__7482(.A (a), .B (b), .Y (n_0));
endmodule

module fag_82(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g61__4733(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g62__6161(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g63__9315(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g64__9945(.A (a), .B (b), .Y (n_0));
endmodule

module fag_81(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__2883(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__2346(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__1666(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__7410(.A (a), .B (b), .Y (n_0));
endmodule

module fag_80(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__6417(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__5477(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__2398(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__5107(.A (a), .B (b), .Y (n_0));
endmodule

module rca8bit_154(s, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  wire UNCONNECTED_HIER_Z;
  fag_56 x1(.s (s[0]), .c (w[1]), .a (a[0]), .b (b[0]), .cin
       (UNCONNECTED_HIER_Z));
  fag_86 x2(.s (s[1]), .c (w[2]), .a (a[1]), .b (b[1]), .cin (w[1]));
  fag_85 x3(.s (s[2]), .c (w[3]), .a (a[2]), .b (b[2]), .cin (w[2]));
  fag_84 x4(.s (s[3]), .c (w[4]), .a (a[3]), .b (b[3]), .cin (w[3]));
  fag_83 x5(.s (s[4]), .c (w[5]), .a (a[4]), .b (b[4]), .cin (w[4]));
  fag_82 x6(.s (s[5]), .c (w[6]), .a (a[5]), .b (b[5]), .cin (w[5]));
  fag_81 x7(.s (s[6]), .c (w[7]), .a (a[6]), .b (b[6]), .cin (w[6]));
  fag_80 x8(.s (s[7]), .c (cout), .a (a[7]), .b (b[7]), .cin (w[7]));
endmodule

module fag_79(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__6260(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__4319(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__8428(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__5526(.A (a), .B (b), .Y (n_0));
endmodule

module fag_78(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__6783(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__3680(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__1617(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__2802(.A (a), .B (b), .Y (n_0));
endmodule

module fag_77(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__1705(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__5122(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__8246(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__7098(.A (a), .B (b), .Y (n_0));
endmodule

module fag_76(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__6131(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__1881(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__5115(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__7482(.A (a), .B (b), .Y (n_0));
endmodule

module fag_75(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__4733(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__6161(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__9315(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__9945(.A (a), .B (b), .Y (n_0));
endmodule

module fag_74(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__2883(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__2346(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__1666(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__7410(.A (a), .B (b), .Y (n_0));
endmodule

module fag_73(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g58__6417(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__5477(.A (cin), .B (n_0), .Y (s));
  OAI21X1 g60__2398(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g61__5107(.A (a), .B (b), .Y (n_0));
endmodule

module fag_72(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_2, n_4, n_5;
  CLKBUFX20 g58(.A (n_5), .Y (c));
  OAI2BB1X4 g59__6260(.A0N (b), .A1N (a), .B0 (n_1), .Y (n_5));
  XOR2X1 g62__4319(.A (a), .B (b), .Y (n_4));
  NAND2X2 g2__5526(.A (cin), .B (n_2), .Y (n_1));
  OR2X2 g3__6783(.A (a), .B (b), .Y (n_2));
  XOR2X1 g64__66(.A (cin), .B (n_4), .Y (s));
endmodule

module rca8bit_4(s, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  fag_79 x1(.s (s[0]), .c (w[1]), .a (a[0]), .b (b[0]), .cin (cin));
  fag_78 x2(.s (s[1]), .c (w[2]), .a (a[1]), .b (b[1]), .cin (w[1]));
  fag_77 x3(.s (s[2]), .c (w[3]), .a (a[2]), .b (b[2]), .cin (w[2]));
  fag_76 x4(.s (s[3]), .c (w[4]), .a (a[3]), .b (b[3]), .cin (w[3]));
  fag_75 x5(.s (s[4]), .c (w[5]), .a (a[4]), .b (b[4]), .cin (w[4]));
  fag_74 x6(.s (s[5]), .c (w[6]), .a (a[5]), .b (b[5]), .cin (w[5]));
  fag_73 x7(.s (s[6]), .c (w[7]), .a (a[6]), .b (b[6]), .cin (w[6]));
  fag_72 x8(.s (s[7]), .c (cout), .a (a[7]), .b (b[7]), .cin (w[7]));
endmodule

module rca16bit(s, cout, a, b, cin);
  input [15:0] a, b;
  input cin;
  output [16:0] s;
  output cout;
  wire [15:0] a, b;
  wire cin;
  wire [16:0] s;
  wire cout;
  wire UNCONNECTED_HIER_Z0, cw;
  rca8bit_154 r0(s[7:0], cw, a[7:0], b[7:0], UNCONNECTED_HIER_Z0);
  rca8bit_4 r1(s[15:8], cout, a[15:8], b[15:8], cw);
endmodule

module fag_56_138(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__3680(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_124(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__1617(.A (a), .B (cin), .CI (b), .S (s), .CO (c));
endmodule

module fag_123(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__2802(.A (a), .B (cin), .CI (b), .S (s), .CO (c));
endmodule

module fag_122(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__1705(.A (a), .B (cin), .CI (b), .S (s), .CO (c));
endmodule

module fag_121(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__5122(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_120(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g62__8246(.A (a), .B (cin), .CI (b), .S (s), .CO (c));
endmodule

module fag_119(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7098(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_118(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g58__6131(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module rca8bit(s, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  wire UNCONNECTED_HIER_Z1;
  fag_56_138 x1(s[0], w[1], a[0], b[0], UNCONNECTED_HIER_Z1);
  fag_124 x2(s[1], w[2], a[1], b[1], w[1]);
  fag_123 x3(s[2], w[3], a[2], b[2], w[2]);
  fag_122 x4(s[3], w[4], a[3], b[3], w[3]);
  fag_121 x5(s[4], w[5], a[4], b[4], w[4]);
  fag_120 x6(s[5], w[6], a[5], b[5], w[5]);
  fag_119 x7(s[6], w[7], a[6], b[6], w[6]);
  fag_118 x8(s[7], cout, a[7], b[7], w[7]);
endmodule

module fag_40(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__1881(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_93(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__5115(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_92(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7482(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_91(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__4733(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_44(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__6161(.A (b), .B (cin), .S (s), .CO (c));
endmodule

module fag_44_135(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__9315(.A (b), .B (cin), .S (s), .CO (c));
endmodule

module fag_44_134(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__9945(.A (b), .B (cin), .S (s), .CO (c));
endmodule

module fag_44_133(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  XOR2X1 g13__2883(.A (cin), .B (b), .Y (s));
endmodule

module rca8bit_1(s, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  wire UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6, n_1;
  fag_40 x1(.s (s[0]), .c (w[1]), .a (a[0]), .b (b[0]), .cin
       (UNCONNECTED_HIER_Z2));
  fag_93 x2(.s (s[1]), .c (w[2]), .a (a[1]), .b (b[1]), .cin (w[1]));
  fag_92 x3(.s (s[2]), .c (w[3]), .a (a[2]), .b (b[2]), .cin (w[2]));
  fag_91 x4(.s (s[3]), .c (w[4]), .a (a[3]), .b (b[3]), .cin (w[3]));
  fag_44 x5(.s (s[4]), .c (w[5]), .a (UNCONNECTED_HIER_Z3), .b (b[4]),
       .cin (w[4]));
  fag_44_135 x6(.s (s[5]), .c (w[6]), .a (UNCONNECTED_HIER_Z4), .b
       (b[5]), .cin (w[5]));
  fag_44_134 x7(.s (s[6]), .c (w[7]), .a (UNCONNECTED_HIER_Z5), .b
       (b[6]), .cin (w[6]));
  fag_44_133 x8(.s (s[7]), .c (n_1), .a (UNCONNECTED_HIER_Z6), .b
       (b[7]), .cin (w[7]));
endmodule

module fag_40_132(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__2346(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_90(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1666(.A (cin), .B (a), .CI (b), .S (s), .CO (c));
endmodule

module fag_89(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7410(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_88(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__6417(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_87(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  CMPR32X1 g58__5477(.A (b), .B (a), .C (cin), .S (s), .CO (c));
endmodule

module fag_55_136(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__2398(.A (a), .B (cin), .S (s), .CO (c));
endmodule

module fag_55_137(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__5107(.A (a), .B (cin), .S (s), .CO (c));
endmodule

module fag_55(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  XOR2X1 g13__6260(.A (cin), .B (a), .Y (s));
endmodule

module rca8bit_2(s, cout, a, b, cin);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  wire UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z10, n_1;
  fag_40_132 x1(.s (s[0]), .c (w[1]), .a (a[0]), .b (b[0]), .cin
       (UNCONNECTED_HIER_Z7));
  fag_90 x2(.s (s[1]), .c (w[2]), .a (a[1]), .b (b[1]), .cin (w[1]));
  fag_89 x3(.s (s[2]), .c (w[3]), .a (a[2]), .b (b[2]), .cin (w[2]));
  fag_88 x4(.s (s[3]), .c (w[4]), .a (a[3]), .b (b[3]), .cin (w[3]));
  fag_87 x5(.s (s[4]), .c (w[5]), .a (a[4]), .b (b[4]), .cin (w[4]));
  fag_55_136 x6(.s (s[5]), .c (w[6]), .a (a[5]), .b
       (UNCONNECTED_HIER_Z8), .cin (w[5]));
  fag_55_137 x7(.s (s[6]), .c (w[7]), .a (a[6]), .b
       (UNCONNECTED_HIER_Z9), .cin (w[6]));
  fag_55 x8(.s (s[7]), .c (n_1), .a (a[7]), .b (UNCONNECTED_HIER_Z10),
       .cin (w[7]));
endmodule

module hag(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1XL g24__4319(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  AND2X2 g25__8428(.A (b), .B (a), .Y (c));
endmodule

module fag(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_2, n_3;
  OAI2BB1X1 g61__5526(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  OAI21XL g63__6783(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  MXI2X1 g65__3680(.S0 (a), .B (b), .A (n_1), .Y (n_2));
  INVX1 g66(.A (b), .Y (n_1));
  XOR2X1 g2__1617(.A (cin), .B (n_2), .Y (s));
endmodule

module hag_153(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1XL g24__2802(.A0N (b), .A1N (a), .B0 (c), .Y (s));
  AND2X2 g25__1705(.A (b), .B (a), .Y (c));
endmodule

module fag_131(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_2;
  OAI2BB1X1 g58__5122(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  OAI21XL g60__8246(.A0 (a), .A1 (b), .B0 (cin), .Y (n_2));
  XOR2X1 g62__7098(.A (b), .B (a), .Y (n_1));
  XOR2X1 g2__6131(.A (cin), .B (n_1), .Y (s));
endmodule

module fag_130(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  OAI2BB1X1 g58__1881(.A0N (b), .A1N (a), .B0 (n_0), .Y (c));
  XOR3X2 g59__5115(.A (b), .B (cin), .C (a), .Y (s));
  OAI21XL g60__7482(.A0 (a), .A1 (b), .B0 (cin), .Y (n_0));
endmodule

module hag_152(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1XL g24__4733(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  AND2X2 g25__6161(.A (a), .B (b), .Y (c));
endmodule

module hag_151(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  CMPR22X1 g24__9315(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_129(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X1 g58__9945(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  XOR2X1 g59__2883(.A (n_0), .B (cin), .Y (s));
  OAI21XL g60__2346(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XOR2X1 g2__1666(.A (a), .B (b), .Y (n_0));
endmodule

module fag_128(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFHX1 g58__7410(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module fag_127(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g58__6417(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_126(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFHX1 g58__5477(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_125(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__2398(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module array4(x, a, b);
  input [3:0] a, b;
  output [7:0] x;
  wire [3:0] a, b;
  wire [7:0] x;
  wire [32:1] w;
  wire n_18, n_19;
  hag h1(x[1], w[3], n_18, w[2]);
  fag h2(w[6], w[9], w[5], n_19, w[3]);
  hag_153 h3(x[2], w[8], w[7], w[6]);
  fag_131 h4(w[12], w[15], w[11], w[10], w[9]);
  fag_130 h5(w[14], w[16], w[12], w[18], w[8]);
  hag_152 h6(x[3], w[17], w[14], w[13]);
  hag_151 h7(w[22], w[24], w[23], w[15]);
  fag_129 h8(w[21], w[26], w[22], w[19], w[16]);
  fag_128 h9(x[4], w[27], w[21], w[20], w[17]);
  fag_127 h10(w[29], w[32], w[24], w[25], w[26]);
  fag_126 h11(x[5], w[30], w[29], w[28], w[27]);
  fag_125 h12(x[6], x[7], w[32], w[31], w[30]);
  AND2X2 g163__5107(.A (a[2]), .B (b[1]), .Y (w[11]));
  AND2X2 g164__6260(.A (a[2]), .B (b[3]), .Y (w[28]));
  AND2X2 g165__4319(.A (a[1]), .B (b[2]), .Y (w[18]));
  AND2X2 g167__5526(.A (a[0]), .B (b[0]), .Y (x[0]));
  AND2X2 g170__3680(.A (a[0]), .B (b[2]), .Y (w[7]));
  AND2X2 g172__1617(.A (a[2]), .B (b[2]), .Y (w[19]));
  AND2X2 g175__2802(.A (a[3]), .B (b[2]), .Y (w[25]));
  AND2X2 g176__1705(.A (a[1]), .B (b[3]), .Y (w[20]));
  AND2X2 g177__5122(.A (a[3]), .B (b[3]), .Y (w[31]));
  AND2X2 g178__8246(.A (a[3]), .B (b[1]), .Y (w[23]));
  AND2X2 g179__7098(.A (a[0]), .B (b[3]), .Y (w[13]));
  AND2X2 g2__6131(.A (a[0]), .B (b[1]), .Y (w[2]));
  AND2X2 g184__1881(.A (a[3]), .B (b[0]), .Y (w[10]));
  AND2X2 g185__5115(.A (b[1]), .B (a[1]), .Y (w[5]));
  AND2X2 g2(.A (a[1]), .B (b[0]), .Y (n_18));
  AND2X2 g186(.A (a[2]), .B (b[0]), .Y (n_19));
endmodule

module hag_150(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1X1 g24__7482(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  AND2X2 g25__4733(.A (b), .B (a), .Y (c));
endmodule

module fag_117(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X1 g58__6161(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  OAI2BB2X1 g59__9315(.A0N (cin), .A1N (n_0), .B0 (n_0), .B1 (cin), .Y
       (s));
  OAI21XL g60__9945(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XNOR2X1 g61__2883(.A (b), .B (a), .Y (n_0));
endmodule

module hag_149(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__2346(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_116(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X1 g58__1666(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  OAI2BB2X1 g59__7410(.A0N (n_0), .A1N (cin), .B0 (cin), .B1 (n_0), .Y
       (s));
  OAI21XL g60__6417(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XNOR2X1 g61__5477(.A (b), .B (a), .Y (n_0));
endmodule

module fag_115(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__2398(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module hag_148(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__5107(.A (b), .B (a), .S (s), .CO (c));
endmodule

module hag_147(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__6260(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_114(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__4319(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_113(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__8428(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_112(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__5526(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_111(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__6783(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_110(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__3680(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module array4_6(x, a, b);
  input [3:0] a, b;
  output [7:0] x;
  wire [3:0] a, b;
  wire [7:0] x;
  wire [32:1] w;
  hag_150 h1(.s (x[1]), .c (w[3]), .a (w[1]), .b (w[2]));
  fag_117 h2(.s (w[6]), .c (w[9]), .a (w[5]), .b (w[4]), .cin (w[3]));
  hag_149 h3(.s (x[2]), .c (w[8]), .a (w[7]), .b (w[6]));
  fag_116 h4(.s (w[12]), .c (w[15]), .a (w[11]), .b (w[10]), .cin
       (w[9]));
  fag_115 h5(.s (w[14]), .c (w[16]), .a (w[12]), .b (w[18]), .cin
       (w[8]));
  hag_148 h6(.s (x[3]), .c (w[17]), .a (w[14]), .b (w[13]));
  hag_147 h7(.s (w[22]), .c (w[24]), .a (w[23]), .b (w[15]));
  fag_114 h8(.s (w[21]), .c (w[26]), .a (w[22]), .b (w[19]), .cin
       (w[16]));
  fag_113 h9(.s (x[4]), .c (w[27]), .a (w[21]), .b (w[20]), .cin
       (w[17]));
  fag_112 h10(.s (w[29]), .c (w[32]), .a (w[24]), .b (w[25]), .cin
       (w[26]));
  fag_111 h11(.s (x[5]), .c (w[30]), .a (w[29]), .b (w[28]), .cin
       (w[27]));
  fag_110 h12(.s (x[6]), .c (x[7]), .a (w[32]), .b (w[31]), .cin
       (w[30]));
  AND2X2 g162__1617(.A (a[2]), .B (b[1]), .Y (w[11]));
  AND2X2 g163__2802(.A (a[2]), .B (b[3]), .Y (w[28]));
  AND2X2 g164__1705(.A (a[1]), .B (b[2]), .Y (w[18]));
  AND2X2 g166__5122(.A (a[0]), .B (b[0]), .Y (x[0]));
  AND2X2 g167__8246(.A (a[2]), .B (b[0]), .Y (w[4]));
  AND2X2 g168__7098(.A (a[3]), .B (b[0]), .Y (w[10]));
  AND2X2 g169__6131(.A (a[0]), .B (b[2]), .Y (w[7]));
  AND2X2 g171__1881(.A (a[2]), .B (b[2]), .Y (w[19]));
  AND2X2 g172__5115(.A (a[1]), .B (b[1]), .Y (w[5]));
  AND2X2 g174__7482(.A (a[3]), .B (b[2]), .Y (w[25]));
  AND2X2 g175__4733(.A (a[1]), .B (b[3]), .Y (w[20]));
  AND2X2 g176__6161(.A (a[3]), .B (b[3]), .Y (w[31]));
  AND2X2 g177__9315(.A (a[3]), .B (b[1]), .Y (w[23]));
  AND2X2 g178__9945(.A (a[0]), .B (b[3]), .Y (w[13]));
  AND2X2 g2__2883(.A (a[1]), .B (b[0]), .Y (w[1]));
  AND2X2 g179__2346(.A (a[0]), .B (b[1]), .Y (w[2]));
endmodule

module hag_146(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1X1 g24__1666(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  AND2X2 g25__7410(.A (b), .B (a), .Y (c));
endmodule

module fag_109(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X1 g58__6417(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  OAI2BB2X1 g59__5477(.A0N (cin), .A1N (n_0), .B0 (n_0), .B1 (cin), .Y
       (s));
  OAI21XL g60__2398(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XNOR2X1 g61__5107(.A (b), .B (a), .Y (n_0));
endmodule

module hag_145(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__6260(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_108(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X1 g58__4319(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  OAI2BB2X1 g59__8428(.A0N (n_0), .A1N (cin), .B0 (cin), .B1 (n_0), .Y
       (s));
  OAI21XL g60__5526(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
  XNOR2X1 g61__6783(.A (b), .B (a), .Y (n_0));
endmodule

module fag_107(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__3680(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module hag_144(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__1617(.A (b), .B (a), .S (s), .CO (c));
endmodule

module hag_143(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__2802(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_106(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1705(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_105(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__5122(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_104(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__8246(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_103(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7098(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_102(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__6131(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module array4_5(x, a, b);
  input [3:0] a, b;
  output [7:0] x;
  wire [3:0] a, b;
  wire [7:0] x;
  wire [32:1] w;
  hag_146 h1(.s (x[1]), .c (w[3]), .a (w[1]), .b (w[2]));
  fag_109 h2(.s (w[6]), .c (w[9]), .a (w[5]), .b (w[4]), .cin (w[3]));
  hag_145 h3(.s (x[2]), .c (w[8]), .a (w[7]), .b (w[6]));
  fag_108 h4(.s (w[12]), .c (w[15]), .a (w[11]), .b (w[10]), .cin
       (w[9]));
  fag_107 h5(.s (w[14]), .c (w[16]), .a (w[12]), .b (w[18]), .cin
       (w[8]));
  hag_144 h6(.s (x[3]), .c (w[17]), .a (w[14]), .b (w[13]));
  hag_143 h7(.s (w[22]), .c (w[24]), .a (w[23]), .b (w[15]));
  fag_106 h8(.s (w[21]), .c (w[26]), .a (w[22]), .b (w[19]), .cin
       (w[16]));
  fag_105 h9(.s (x[4]), .c (w[27]), .a (w[21]), .b (w[20]), .cin
       (w[17]));
  fag_104 h10(.s (w[29]), .c (w[32]), .a (w[24]), .b (w[25]), .cin
       (w[26]));
  fag_103 h11(.s (x[5]), .c (w[30]), .a (w[29]), .b (w[28]), .cin
       (w[27]));
  fag_102 h12(.s (x[6]), .c (x[7]), .a (w[32]), .b (w[31]), .cin
       (w[30]));
  AND2X2 g162__1881(.A (a[2]), .B (b[1]), .Y (w[11]));
  AND2X2 g163__5115(.A (a[2]), .B (b[3]), .Y (w[28]));
  AND2X2 g164__7482(.A (a[1]), .B (b[2]), .Y (w[18]));
  AND2X2 g166__4733(.A (a[0]), .B (b[0]), .Y (x[0]));
  AND2X2 g167__6161(.A (a[2]), .B (b[0]), .Y (w[4]));
  AND2X2 g168__9315(.A (a[3]), .B (b[0]), .Y (w[10]));
  AND2X2 g169__9945(.A (a[0]), .B (b[2]), .Y (w[7]));
  AND2X2 g171__2883(.A (a[2]), .B (b[2]), .Y (w[19]));
  AND2X2 g172__2346(.A (a[1]), .B (b[1]), .Y (w[5]));
  AND2X2 g174__1666(.A (a[3]), .B (b[2]), .Y (w[25]));
  AND2X2 g175__7410(.A (a[1]), .B (b[3]), .Y (w[20]));
  AND2X2 g176__6417(.A (a[3]), .B (b[3]), .Y (w[31]));
  AND2X2 g177__5477(.A (a[3]), .B (b[1]), .Y (w[23]));
  AND2X2 g178__2398(.A (a[0]), .B (b[3]), .Y (w[13]));
  AND2X2 g2__5107(.A (a[1]), .B (b[0]), .Y (w[1]));
  AND2X2 g179__6260(.A (a[0]), .B (b[1]), .Y (w[2]));
endmodule

module hag_142(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__4319(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_101(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__8428(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_141(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__5526(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_100(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__6783(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_99(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__3680(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module hag_140(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__1617(.A (b), .B (a), .S (s), .CO (c));
endmodule

module hag_139(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__2802(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_98(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1705(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_97(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g58__5122(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_96(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__8246(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_95(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7098(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_94(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__6131(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module array4_4(x, a, b);
  input [3:0] a, b;
  output [7:0] x;
  wire [3:0] a, b;
  wire [7:0] x;
  wire [32:1] w;
  hag_142 h1(.s (x[1]), .c (w[3]), .a (w[1]), .b (w[2]));
  fag_101 h2(.s (w[6]), .c (w[9]), .a (w[5]), .b (w[4]), .cin (w[3]));
  hag_141 h3(.s (x[2]), .c (w[8]), .a (w[7]), .b (w[6]));
  fag_100 h4(.s (w[12]), .c (w[15]), .a (w[11]), .b (w[10]), .cin
       (w[9]));
  fag_99 h5(.s (w[14]), .c (w[16]), .a (w[12]), .b (w[18]), .cin
       (w[8]));
  hag_140 h6(.s (x[3]), .c (w[17]), .a (w[14]), .b (w[13]));
  hag_139 h7(.s (w[22]), .c (w[24]), .a (w[23]), .b (w[15]));
  fag_98 h8(.s (w[21]), .c (w[26]), .a (w[22]), .b (w[19]), .cin
       (w[16]));
  fag_97 h9(.s (x[4]), .c (w[27]), .a (w[21]), .b (w[20]), .cin
       (w[17]));
  fag_96 h10(.s (w[29]), .c (w[32]), .a (w[24]), .b (w[25]), .cin
       (w[26]));
  fag_95 h11(.s (x[5]), .c (w[30]), .a (w[29]), .b (w[28]), .cin
       (w[27]));
  fag_94 h12(.s (x[6]), .c (x[7]), .a (w[32]), .b (w[31]), .cin
       (w[30]));
  AND2X2 g161__1881(.A (a[2]), .B (b[1]), .Y (w[11]));
  AND2X2 g162__5115(.A (a[2]), .B (b[3]), .Y (w[28]));
  AND2X2 g163__7482(.A (a[1]), .B (b[2]), .Y (w[18]));
  AND2X2 g164__4733(.A (a[1]), .B (b[0]), .Y (w[1]));
  AND2X2 g165__6161(.A (a[0]), .B (b[0]), .Y (x[0]));
  AND2X2 g166__9315(.A (a[2]), .B (b[0]), .Y (w[4]));
  AND2X2 g167__9945(.A (a[3]), .B (b[0]), .Y (w[10]));
  AND2X2 g168__2883(.A (a[0]), .B (b[2]), .Y (w[7]));
  AND2X2 g169__2346(.A (a[2]), .B (b[2]), .Y (w[19]));
  AND2X2 g170__1666(.A (a[1]), .B (b[1]), .Y (w[5]));
  AND2X2 g171__7410(.A (a[0]), .B (b[1]), .Y (w[2]));
  AND2X2 g172__6417(.A (a[3]), .B (b[2]), .Y (w[25]));
  AND2X2 g173__5477(.A (a[1]), .B (b[3]), .Y (w[20]));
  AND2X2 g174__2398(.A (a[3]), .B (b[3]), .Y (w[31]));
  AND2X2 g175__5107(.A (a[3]), .B (b[1]), .Y (w[23]));
  AND2X2 g176__6260(.A (a[0]), .B (b[3]), .Y (w[13]));
endmodule

module array8(t, a, b);
  input [7:0] a, b;
  output [15:0] t;
  wire [7:0] a, b;
  wire [15:0] t;
  wire [7:0] w1;
  wire [7:0] w2;
  wire [7:0] w4;
  wire [7:0] w;
  wire [7:0] w5;
  wire [7:0] w3;
  wire UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18;
  wire UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20, ca1, ca2, ca3;
  rca8bit n1(w4, ca1, w1, w2, UNCONNECTED_HIER_Z11);
  rca8bit_1 n2({w5[7:4], t[7:4]}, ca2, {UNCONNECTED_HIER_Z15,
       UNCONNECTED_HIER_Z14, UNCONNECTED_HIER_Z13,
       UNCONNECTED_HIER_Z12, w[7:4]}, w4, UNCONNECTED_HIER_Z16);
  rca8bit_2 n3(t[15:8], ca3, w3, {UNCONNECTED_HIER_Z19,
       UNCONNECTED_HIER_Z18, UNCONNECTED_HIER_Z17, ca1, w5[7:4]},
       UNCONNECTED_HIER_Z20);
  array4 x1({w[7:4], t[3:0]}, a[3:0], b[3:0]);
  array4_6 x2(w1, a[3:0], b[7:4]);
  array4_5 x3(w2, a[7:4], b[3:0]);
  array4_4 x4(w3, a[7:4], b[7:4]);
endmodule

module mac16arr(ac_val, cout, a, b, clk, rst, en);
  input [7:0] a, b;
  input clk, rst, en;
  output [15:0] ac_val;
  output cout;
  wire [7:0] a, b;
  wire clk, rst, en;
  wire [15:0] ac_val;
  wire cout;
  wire [15:0] pipo;
  wire [15:0] product;
  wire [15:0] s;
  wire [15:0] p;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED_HIER_Z21, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  rca16bit s1({UNCONNECTED, s}, cout, {pipo[15:4], ac_val[3],
       pipo[2:1], ac_val[0]}, product, UNCONNECTED_HIER_Z21);
  array8 v1(p, a, b);
  BUFX3 g102(.A (pipo[10]), .Y (ac_val[10]));
  BUFX3 g107(.A (pipo[6]), .Y (ac_val[6]));
  BUFX3 g105(.A (pipo[8]), .Y (ac_val[8]));
  BUFX3 g112(.A (pipo[1]), .Y (ac_val[1]));
  BUFX3 g110(.A (pipo[11]), .Y (ac_val[11]));
  BUFX3 g100(.A (pipo[15]), .Y (ac_val[15]));
  BUFX3 g113(.A (pipo[2]), .Y (ac_val[2]));
  BUFX3 g108(.A (pipo[13]), .Y (ac_val[13]));
  BUFX3 g101(.A (pipo[7]), .Y (ac_val[7]));
  BUFX3 g111(.A (pipo[4]), .Y (ac_val[4]));
  BUFX3 g106(.A (pipo[12]), .Y (ac_val[12]));
  BUFX3 g115(.A (pipo[5]), .Y (ac_val[5]));
  BUFX3 g104(.A (pipo[14]), .Y (ac_val[14]));
  BUFX3 g109(.A (pipo[9]), .Y (ac_val[9]));
  DFFNXL \product_reg[15] (.CKN (clk), .D (n_33), .Q (product[15]), .QN
       (UNCONNECTED0));
  DFFNX4 \product_reg[1] (.CKN (clk), .D (n_53), .Q (product[1]), .QN
       (UNCONNECTED1));
  DFFNX4 \product_reg[2] (.CKN (clk), .D (n_52), .Q (product[2]), .QN
       (UNCONNECTED2));
  DFFNX2 \product_reg[3] (.CKN (clk), .D (n_50), .Q (product[3]), .QN
       (UNCONNECTED3));
  DFFNX2 \product_reg[4] (.CKN (clk), .D (n_49), .Q (product[4]), .QN
       (UNCONNECTED4));
  DFFNX2 \product_reg[5] (.CKN (clk), .D (n_48), .Q (product[5]), .QN
       (UNCONNECTED5));
  DFFNX1 \product_reg[6] (.CKN (clk), .D (n_46), .Q (product[6]), .QN
       (UNCONNECTED6));
  DFFNX1 \product_reg[7] (.CKN (clk), .D (n_45), .Q (product[7]), .QN
       (UNCONNECTED7));
  DFFNX1 \product_reg[8] (.CKN (clk), .D (n_30), .Q (product[8]), .QN
       (UNCONNECTED8));
  DFFNX1 \product_reg[9] (.CKN (clk), .D (n_42), .Q (product[9]), .QN
       (UNCONNECTED9));
  DFFNX1 \product_reg[10] (.CKN (clk), .D (n_40), .Q (product[10]), .QN
       (UNCONNECTED10));
  DFFNX1 \product_reg[11] (.CKN (clk), .D (n_39), .Q (product[11]), .QN
       (UNCONNECTED11));
  DFFNX1 \product_reg[12] (.CKN (clk), .D (n_38), .Q (product[12]), .QN
       (UNCONNECTED12));
  DFFNX1 \product_reg[13] (.CKN (clk), .D (n_37), .Q (product[13]), .QN
       (UNCONNECTED13));
  DFFNX1 \product_reg[14] (.CKN (clk), .D (n_34), .Q (product[14]), .QN
       (UNCONNECTED14));
  DFFNX4 \product_reg[0] (.CKN (clk), .D (n_55), .Q (product[0]), .QN
       (UNCONNECTED15));
  DFFHQX1 \ac_val_reg[10] (.CK (clk), .D (n_31), .Q (pipo[10]));
  EDFFTRX1 \ac_val_reg[12] (.CK (clk), .D (s[12]), .E (en), .RN (n_1),
       .Q (pipo[12]), .QN (UNCONNECTED16));
  EDFFTRX1 \ac_val_reg[13] (.CK (clk), .D (s[13]), .E (en), .RN (n_1),
       .Q (pipo[13]), .QN (UNCONNECTED17));
  EDFFTRX1 \ac_val_reg[14] (.CK (clk), .D (s[14]), .E (en), .RN (n_1),
       .Q (pipo[14]), .QN (UNCONNECTED18));
  DFFHQX2 \ac_val_reg[1] (.CK (clk), .D (n_56), .Q (pipo[1]));
  DFFHQX1 \ac_val_reg[11] (.CK (clk), .D (n_43), .Q (pipo[11]));
  EDFFTRX1 \ac_val_reg[15] (.CK (clk), .D (s[15]), .E (en), .RN (n_1),
       .Q (pipo[15]), .QN (UNCONNECTED19));
  DFFHQX2 \ac_val_reg[2] (.CK (clk), .D (n_54), .Q (pipo[2]));
  DFFHQX2 \ac_val_reg[3] (.CK (clk), .D (n_51), .Q (ac_val[3]));
  DFFHQX2 \ac_val_reg[4] (.CK (clk), .D (n_47), .Q (pipo[4]));
  DFFHQX1 \ac_val_reg[6] (.CK (clk), .D (n_41), .Q (pipo[6]));
  DFFHQX2 \ac_val_reg[5] (.CK (clk), .D (n_57), .Q (pipo[5]));
  DFFHQX1 \ac_val_reg[7] (.CK (clk), .D (n_36), .Q (pipo[7]));
  DFFHQX1 \ac_val_reg[8] (.CK (clk), .D (n_35), .Q (pipo[8]));
  DFFHQX1 \ac_val_reg[9] (.CK (clk), .D (n_32), .Q (pipo[9]));
  DFFHQX2 \ac_val_reg[0] (.CK (clk), .D (n_44), .Q (ac_val[0]));
  NOR2X1 g132__4319(.A (rst), .B (n_2), .Y (n_57));
  NOR2X1 g133__8428(.A (rst), .B (n_28), .Y (n_56));
  NOR2X1 g134__5526(.A (rst), .B (n_27), .Y (n_55));
  NOR2X1 g135__6783(.A (rst), .B (n_22), .Y (n_54));
  NOR2X1 g136__3680(.A (rst), .B (n_26), .Y (n_53));
  NOR2X1 g137__1617(.A (rst), .B (n_24), .Y (n_52));
  NOR2X1 g138__2802(.A (rst), .B (n_21), .Y (n_51));
  NOR2X1 g139__1705(.A (rst), .B (n_23), .Y (n_50));
  NOR2X1 g140__5122(.A (rst), .B (n_20), .Y (n_49));
  NOR2X1 g141__8246(.A (rst), .B (n_19), .Y (n_48));
  NOR2X1 g142__7098(.A (rst), .B (n_17), .Y (n_47));
  NOR2X1 g143__6131(.A (rst), .B (n_18), .Y (n_46));
  NOR2X1 g144__1881(.A (rst), .B (n_29), .Y (n_45));
  NOR2X1 g145__5115(.A (rst), .B (n_25), .Y (n_44));
  NOR2X1 g146__7482(.A (rst), .B (n_15), .Y (n_43));
  NOR2X1 g147__4733(.A (rst), .B (n_14), .Y (n_42));
  NOR2X1 g148__6161(.A (rst), .B (n_13), .Y (n_41));
  NOR2X1 g149__9315(.A (rst), .B (n_12), .Y (n_40));
  NOR2X1 g150__9945(.A (rst), .B (n_11), .Y (n_39));
  NOR2X1 g151__2883(.A (rst), .B (n_9), .Y (n_38));
  NOR2X1 g152__2346(.A (rst), .B (n_8), .Y (n_37));
  NOR2X1 g153__1666(.A (rst), .B (n_10), .Y (n_36));
  NOR2X1 g154__7410(.A (rst), .B (n_6), .Y (n_35));
  NOR2XL g155__6417(.A (rst), .B (n_7), .Y (n_34));
  NOR2XL g156__5477(.A (n_4), .B (rst), .Y (n_33));
  NOR2X1 g157__2398(.A (rst), .B (n_5), .Y (n_32));
  NOR2X1 g158__5107(.A (rst), .B (n_3), .Y (n_31));
  NOR2X1 g159__6260(.A (rst), .B (n_16), .Y (n_30));
  AOI22X1 g160__4319(.A0 (n_0), .A1 (product[7]), .B0 (p[7]), .B1 (en),
       .Y (n_29));
  AOI22X1 g161__8428(.A0 (n_0), .A1 (pipo[1]), .B0 (en), .B1 (s[1]), .Y
       (n_28));
  AOI22XL g162__5526(.A0 (n_0), .A1 (product[0]), .B0 (p[0]), .B1 (en),
       .Y (n_27));
  AOI22X1 g163__6783(.A0 (n_0), .A1 (product[1]), .B0 (p[1]), .B1 (en),
       .Y (n_26));
  AOI22X1 g164__3680(.A0 (n_0), .A1 (ac_val[0]), .B0 (en), .B1 (s[0]),
       .Y (n_25));
  AOI22X1 g165__1617(.A0 (n_0), .A1 (product[2]), .B0 (p[2]), .B1 (en),
       .Y (n_24));
  AOI22X1 g166__2802(.A0 (n_0), .A1 (product[3]), .B0 (p[3]), .B1 (en),
       .Y (n_23));
  AOI22X1 g167__1705(.A0 (n_0), .A1 (pipo[2]), .B0 (en), .B1 (s[2]), .Y
       (n_22));
  AOI22X1 g168__5122(.A0 (n_0), .A1 (ac_val[3]), .B0 (en), .B1 (s[3]),
       .Y (n_21));
  AOI22X1 g169__8246(.A0 (n_0), .A1 (product[4]), .B0 (p[4]), .B1 (en),
       .Y (n_20));
  AOI22X1 g170__7098(.A0 (n_0), .A1 (product[5]), .B0 (p[5]), .B1 (en),
       .Y (n_19));
  AOI22X1 g171__6131(.A0 (n_0), .A1 (product[6]), .B0 (p[6]), .B1 (en),
       .Y (n_18));
  AOI22X1 g172__1881(.A0 (n_0), .A1 (pipo[4]), .B0 (en), .B1 (s[4]), .Y
       (n_17));
  AOI22X1 g173__5115(.A0 (n_0), .A1 (product[8]), .B0 (p[8]), .B1 (en),
       .Y (n_16));
  AOI22X1 g174__7482(.A0 (n_0), .A1 (pipo[11]), .B0 (en), .B1 (s[11]),
       .Y (n_15));
  AOI22X1 g175__4733(.A0 (n_0), .A1 (product[9]), .B0 (p[9]), .B1 (en),
       .Y (n_14));
  AOI22X1 g176__6161(.A0 (n_0), .A1 (pipo[6]), .B0 (en), .B1 (s[6]), .Y
       (n_13));
  AOI22X1 g177__9315(.A0 (n_0), .A1 (product[10]), .B0 (p[10]), .B1
       (en), .Y (n_12));
  AOI22X1 g178__9945(.A0 (n_0), .A1 (product[11]), .B0 (p[11]), .B1
       (en), .Y (n_11));
  AOI22X1 g179__2883(.A0 (n_0), .A1 (pipo[7]), .B0 (en), .B1 (s[7]), .Y
       (n_10));
  AOI22X1 g180__2346(.A0 (n_0), .A1 (product[12]), .B0 (p[12]), .B1
       (en), .Y (n_9));
  AOI22X1 g181__1666(.A0 (n_0), .A1 (product[13]), .B0 (p[13]), .B1
       (en), .Y (n_8));
  AOI22X1 g182__7410(.A0 (n_0), .A1 (product[14]), .B0 (p[14]), .B1
       (en), .Y (n_7));
  AOI22X1 g183__6417(.A0 (n_0), .A1 (pipo[8]), .B0 (en), .B1 (s[8]), .Y
       (n_6));
  AOI22X1 g184__5477(.A0 (n_0), .A1 (pipo[9]), .B0 (en), .B1 (s[9]), .Y
       (n_5));
  AOI22X1 g185__2398(.A0 (n_0), .A1 (product[15]), .B0 (p[15]), .B1
       (en), .Y (n_4));
  AOI22X1 g186__5107(.A0 (n_0), .A1 (pipo[10]), .B0 (en), .B1 (s[10]),
       .Y (n_3));
  AOI22X1 g187__6260(.A0 (n_0), .A1 (pipo[5]), .B0 (en), .B1 (s[5]), .Y
       (n_2));
  INVX1 g188(.A (rst), .Y (n_1));
  INVX1 g189(.A (en), .Y (n_0));
endmodule

